## Calculate Covariance matrix

### 1. With Numpy (np.cov)

In [8]:
import numpy as np

### Defining a matric X with 3 observations and 5 parameters. Covariance matric will be created with n*n where n = number of parameters 

In [9]:
X = np.array([ [0.1, 0.3, 0.4, 0.8, 0.9],
               [3.2, 2.4, 2.4, 0.1, 5.5],
               [10., 8.2, 4.3, 2.6, 0.9]
             ])
X

array([[ 0.1,  0.3,  0.4,  0.8,  0.9],
       [ 3.2,  2.4,  2.4,  0.1,  5.5],
       [10. ,  8.2,  4.3,  2.6,  0.9]])

In [10]:
np.cov(X.T)

array([[25.64333333, 20.69333333,  9.62166667,  5.44166667, -2.83666667],
       [20.69333333, 16.74333333,  7.67166667,  4.54166667, -2.83666667],
       [ 9.62166667,  7.67166667,  3.80333333,  1.72833333,  0.07666667],
       [ 5.44166667,  4.54166667,  1.72833333,  1.66333333, -2.45333333],
       [-2.83666667, -2.83666667,  0.07666667, -2.45333333,  7.05333333]])

### 2. Dot product
<br>
<center>
    $$Q_n = \frac{1}{n}\sum_{i=1}^{n} (x_i - \bar{x})(x_i - \bar{x})^T$$

In [11]:
m = np.mean(X, axis=0, keepdims=True)

In [12]:
m

array([[4.43333333, 3.63333333, 2.36666667, 1.16666667, 2.43333333]])

In [13]:
x = np.dot((X - m).T, X - m) / (X.shape[0] - 1)
x

array([[25.64333333, 20.69333333,  9.62166667,  5.44166667, -2.83666667],
       [20.69333333, 16.74333333,  7.67166667,  4.54166667, -2.83666667],
       [ 9.62166667,  7.67166667,  3.80333333,  1.72833333,  0.07666667],
       [ 5.44166667,  4.54166667,  1.72833333,  1.66333333, -2.45333333],
       [-2.83666667, -2.83666667,  0.07666667, -2.45333333,  7.05333333]])