<a href="https://colab.research.google.com/github/sum-coderepo/DeepLearning-Pytorch/blob/master/PytorchTutorials/Tensors_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
my_tensors = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32,device = device , requires_grad= True)

In [9]:
my_tensors.device, my_tensors.requires_grad, my_tensors.shape

(device(type='cpu'), True, torch.Size([2, 3]))

# Other Initialization Mthods

In [12]:
x = torch.empty(size = (3,3))
print(x)

tensor([[7.0176e-35, 0.0000e+00, 1.4013e-45],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1286e+27, 1.7743e+28, 2.0535e-19]])


In [13]:
x = torch.zeros(size = (3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [14]:
x = torch.rand(size = (3,3))
print(x)

tensor([[0.8413, 0.7136, 0.3299],
        [0.6356, 0.4087, 0.1981],
        [0.0897, 0.2475, 0.6699]])


In [15]:
x= torch.ones(size = (3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
#identity Matrix
x = torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [18]:
x = torch.arange(start = 0, end = 1, step = 10)
print(x)

tensor([0])


In [20]:
x = torch.linspace(start = 0.1, end = 1, steps = 10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [21]:
x = torch.empty(size = (1,5)).normal_(mean = 0, std = 1)
print(x)

tensor([[-1.5409,  0.9917, -0.0016,  1.4341,  0.7362]])


In [23]:
x = torch.empty(size = (1,5)).uniform_( 0,  1)
print(x)

tensor([[0.6603, 0.2376, 0.9131, 0.2137, 0.4551]])


In [24]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [25]:
tensor = torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


In [31]:
print(tensor.float())
print(tensor.short())
print(tensor.half())
print(tensor.double())
print(tensor.half())

tensor([0., 1., 2., 3.])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0., 1., 2., 3.], dtype=torch.float16)


Convert to Tensor from Numpy Array

In [32]:
import numpy as np

In [38]:
np_array = np.zeros((5,5))
print(np_array)
tensor = torch.from_numpy(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Convert to Numpy Arrar from tensors

In [37]:
numpy_arr_bk  = tensor.numpy()
print(numpy_arr_bk)

[0 1 2 3]


## Math and Comparison

In [39]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8 , 7])

In [40]:
# Addition
z1 = torch.empty(3)
torch.add(x,y, out = z1)
z2 = torch.add(x,y)
z = x+y

In [41]:
# Substraction
z = x-y
print(z)

tensor([-8, -6, -4])


In [42]:
# Division
z = torch.true_divide(x,y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [46]:
# Inplace operations
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([1., 2., 3.])


In [47]:
t += x
print(t)

tensor([2., 4., 6.])


In [49]:
# Exponentiation
z = x.pow(2)
print(z)
z = x ** 2
print(z)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [51]:
# Comparison
z = x > 0
z

tensor([True, True, True])

In [53]:
# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x = torch.mm(x1, x2)
x3 = x1.mm(x2)
print(x)

tensor([[1.1999, 1.3216, 1.4146],
        [1.1022, 1.4130, 1.1960]])


In [54]:
# Matrix Exponentaition
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[3.0167, 2.1203, 3.0362, 2.2370, 3.4211],
        [5.4170, 3.8535, 5.4770, 3.9830, 6.2188],
        [4.7626, 3.3549, 4.8176, 3.5088, 5.4250],
        [6.2555, 4.5024, 6.4147, 4.6993, 7.2032],
        [5.1443, 3.5926, 5.1648, 3.7704, 5.8858]])


In [55]:
# Element wise mult
z = x * y
print(z)

tensor([[10.7989, 10.5726,  9.9024],
        [ 9.9194, 11.3040,  8.3717]])


In [62]:
# dot product
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
z = torch.dot(x.view(-1),y.view(-1))
print(z)

tensor(46)


In [66]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bnm = torch.bmm(tensor1, tensor2) # (batch, n, p)
print(out_bnm)

tensor([[[5.3675, 5.7151, 5.0869,  ..., 4.6606, 4.9482, 5.3540],
         [4.0976, 3.9877, 3.9204,  ..., 3.2720, 3.3972, 3.8431],
         [4.4802, 4.2235, 3.7296,  ..., 5.1053, 4.4611, 5.1983],
         ...,
         [3.5892, 3.5182, 2.7512,  ..., 2.9290, 3.9132, 3.9677],
         [4.8670, 4.6213, 4.1678,  ..., 4.4448, 4.6724, 5.1957],
         [5.0269, 5.1212, 4.0964,  ..., 5.0042, 4.8650, 4.8590]],

        [[4.8657, 6.5958, 4.8835,  ..., 6.1438, 6.1228, 4.8888],
         [4.9039, 5.8194, 3.8613,  ..., 4.9002, 5.7806, 3.8437],
         [3.0559, 4.4767, 3.1601,  ..., 3.5245, 4.2160, 2.7587],
         ...,
         [3.7357, 4.6189, 3.5983,  ..., 4.2058, 4.7819, 3.8262],
         [4.9819, 6.6932, 4.1788,  ..., 6.0668, 5.6041, 3.8637],
         [4.5576, 6.9206, 4.3509,  ..., 5.7075, 6.4605, 4.3517]],

        [[5.7926, 6.9736, 4.9422,  ..., 6.5580, 6.7413, 6.2398],
         [5.2583, 5.4902, 4.0289,  ..., 5.0473, 5.7521, 4.9493],
         [5.9326, 6.6893, 4.2433,  ..., 5.0891, 5.6045, 6.

In [67]:
out_bnm.shape

torch.Size([32, 10, 30])

In [68]:
# Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
print(x1),print(x2)

tensor([[0.6238, 0.0879, 0.8824, 0.7231, 0.9103],
        [0.6001, 0.1377, 0.8356, 0.9631, 0.4799],
        [0.4734, 0.4250, 0.2099, 0.4212, 0.2647],
        [0.3993, 0.1917, 0.4427, 0.7784, 0.1165],
        [0.0131, 0.2620, 0.9760, 0.4110, 0.3114]])
tensor([[0.6770, 0.1287, 0.7203, 0.9133, 0.9888]])


(None, None)

In [70]:
z = x1 - x2
z1 = x1 ** x2
print(z), print(z1)

tensor([[-0.0533, -0.0407,  0.1621, -0.1903, -0.0785],
        [-0.0770,  0.0091,  0.1154,  0.0498, -0.5090],
        [-0.2036,  0.2963, -0.5104, -0.4922, -0.7241],
        [-0.2778,  0.0630, -0.2776, -0.1349, -0.8723],
        [-0.6640,  0.1333,  0.2557, -0.5023, -0.6775]])
tensor([[0.7265, 0.7314, 0.9138, 0.7437, 0.9113],
        [0.7077, 0.7749, 0.8787, 0.9662, 0.4838],
        [0.6027, 0.8957, 0.3248, 0.4539, 0.2687],
        [0.5371, 0.8085, 0.5560, 0.7955, 0.1194],
        [0.0531, 0.8417, 0.9826, 0.4439, 0.3155]])


(None, None)

# Other Tensor Operations

In [73]:
sum_x_0 = torch.sum(x, dim =0) ## dim = 0 Row wise
print(sum_x_0)

tensor(6)


In [74]:
value, indices = torch.max(x, dim =0)
print(value, indices)

tensor(3) tensor(2)


In [75]:
# Absolute value 
abs_x = torch.abs(x)
x = torch.argmax(x, dim = 0)
print(x) ## Return only index


tensor(2)


In [76]:
# Mean
mean_x = torch.mean(x.float(), dim =0)
print(mean_x)

tensor(2.)


In [77]:
# Check Equal
z = torch.eq(x,y)
z

tensor([False, False, False])

In [78]:
# Sort
sorted_y, indices = torch.sort(y, dim = 0, descending= False)
print(sorted_y)

tensor([7, 8, 9])


In [79]:
# Clamp
z = torch.clamp(x, min = 0, max = 10) # Any value less than 0 will be set to 0 and any value more than 10 will be set to 10.
print(z)

tensor(2)


# **Indexing**

In [83]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
print(x[0].shape), print(x[:,0].shape) # First print the all features for first example and second one prints the first features of all the examples.


torch.Size([25])
torch.Size([10])


(None, None)

In [85]:
print(x[2,0:10]) # Second row and 0-10 columns

tensor([0.0910, 0.3832, 0.0338, 0.4766, 0.3345, 0.4057, 0.6403, 0.2227, 0.8429,
        0.1644])


In [87]:
# Fancy indexing
x = torch.arange(10)
indices = [2,5,8] # Print 3rd, 6th and 9th value
print(x[indices])

tensor([2, 5, 8])


In [90]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows, cols]) # Print 2nd row 4th col and 1st Row and 1st col

tensor([0.4626, 0.5282])


In [94]:
# More Advanced Indexing
x = torch.arange(10)
print(x[(x > 2) & (x< 8)]) # Print values more than 2 and less than 8.
print(x[x.remainder(2)== 0]) # Print if the digits are even numbers.

tensor([3, 4, 5, 6, 7])
tensor([0, 2, 4, 6, 8])


In [97]:
print(torch.where(x > 5, x, x*2)) # Print if the value is less than 5 than 5 * x else x
print(x.ndimension())
print(x.numel()) # Number of values

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
1
10


# Reshaping the Tensors

In [99]:
x = torch.arange(9)
x_v = x.view(3,3)
x_rs = x.reshape(3,3)
print(x_v), print(x_rs)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


(None, None)

In [101]:
print(x_v.t()) #Transpose

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [102]:
print(x_v.reshape(9))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [108]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(x1), print(x2)
print(torch.cat((x1,x2), dim = 0))
print(torch.cat((x1,x2), dim = 1))

tensor([[0.4649, 0.1996, 0.8049, 0.8545, 0.8633],
        [0.7423, 0.3477, 0.9109, 0.1643, 0.5575]])
tensor([[0.5540, 0.1089, 0.9281, 0.8734, 0.4266],
        [0.2191, 0.1718, 0.9313, 0.4503, 0.6189]])
tensor([[0.4649, 0.1996, 0.8049, 0.8545, 0.8633],
        [0.7423, 0.3477, 0.9109, 0.1643, 0.5575],
        [0.5540, 0.1089, 0.9281, 0.8734, 0.4266],
        [0.2191, 0.1718, 0.9313, 0.4503, 0.6189]])
tensor([[0.4649, 0.1996, 0.8049, 0.8545, 0.8633, 0.5540, 0.1089, 0.9281, 0.8734,
         0.4266],
        [0.7423, 0.3477, 0.9109, 0.1643, 0.5575, 0.2191, 0.1718, 0.9313, 0.4503,
         0.6189]])


In [109]:
z = x1.view(-1)
print(z)

tensor([0.4649, 0.1996, 0.8049, 0.8545, 0.8633, 0.7423, 0.3477, 0.9109, 0.1643,
        0.5575])


In [110]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [111]:
# Permute V.Important
# swap 2nd and 3rd dimesnion
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [117]:
# Unsqueeze
# Returns a new tensor with a dimension of size one inserted at the specified position.
# The returned tensor shares the same underlying data with this tensor.
# A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.
x = torch.arange(10)
y = x.unsqueeze(0)
print(y.shape)
print(y)
y = x.unsqueeze(1)
print(y.shape)
print(y)

torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
