<a href="https://colab.research.google.com/github/sum-coderepo/DeepLearning-Pytorch/blob/master/PytorchTutorials/Tensors_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
my_tensors = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32,device = device , requires_grad= True)

In [9]:
my_tensors.device, my_tensors.requires_grad, my_tensors.shape

(device(type='cpu'), True, torch.Size([2, 3]))

# Other Initialization Mthods

In [12]:
x = torch.empty(size = (3,3))
print(x)

tensor([[7.0176e-35, 0.0000e+00, 1.4013e-45],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1286e+27, 1.7743e+28, 2.0535e-19]])


In [13]:
x = torch.zeros(size = (3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [14]:
x = torch.rand(size = (3,3))
print(x)

tensor([[0.8413, 0.7136, 0.3299],
        [0.6356, 0.4087, 0.1981],
        [0.0897, 0.2475, 0.6699]])


In [15]:
x= torch.ones(size = (3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
#identity Matrix
x = torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [18]:
x = torch.arange(start = 0, end = 1, step = 10)
print(x)

tensor([0])


In [20]:
x = torch.linspace(start = 0.1, end = 1, steps = 10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [21]:
x = torch.empty(size = (1,5)).normal_(mean = 0, std = 1)
print(x)

tensor([[-1.5409,  0.9917, -0.0016,  1.4341,  0.7362]])


In [23]:
x = torch.empty(size = (1,5)).uniform_( 0,  1)
print(x)

tensor([[0.6603, 0.2376, 0.9131, 0.2137, 0.4551]])


In [24]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [25]:
tensor = torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


In [31]:
print(tensor.float())
print(tensor.short())
print(tensor.half())
print(tensor.double())
print(tensor.half())

tensor([0., 1., 2., 3.])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0., 1., 2., 3.], dtype=torch.float16)


Convert to Tensor from Numpy Array

In [32]:
import numpy as np

In [38]:
np_array = np.zeros((5,5))
print(np_array)
tensor = torch.from_numpy(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Convert to Numpy Arrar from tensors

In [37]:
numpy_arr_bk  = tensor.numpy()
print(numpy_arr_bk)

[0 1 2 3]


## Math and Comparison